### ISSUE TITLE
Shoot function

### ISSUE THREAD

**Issue by nleighton11** [nleighton11/7870E-Turning-Point#2]
For the format of calling a function using "Pressed" has to include the void, so yours would look like
Controller.ButtonX.Pressed(void(Shoot));

**Comment by nleighton11** [comment]
Scratch everything I just said, there is a weird format for it though.

**Comment by nleighton11** [comment]
I got It lol, its just
Controller.ButtonX.Pressed(Shoot);

**Comment by IanJuneau** [comment]
So you mean. It’s exactly how I coded it the first time?
